name: Daily Very-Useful Channel

on:
  schedule:
    - cron: '0-59 18 * * 6' # ЦБРФ данные
    - cron: '1-58 18 * * 6'  # Мосбиржа данные
  push:
    branches:
      - main 

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CENNAL_ID: ${{ secrets.TELEGRAM_CENNAL_ID }}

jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run App
        run: python app.py