name: Daily Very-Useful Channel

on:
  schedule:
    - cron: '55 16 * * 1-5' # ЦБРФ данные в 18:15 по Москве (11:01 UTC) по будням
    - cron: '59 16 * * 1-5' # Мосбиржа данные в 18:25 по Москве (11:10 UTC) по будням
  push:
    branches:
      - main

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CENNAL_ID: ${{ secrets.TELEGRAM_CENNAL_ID }}

jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Ensure State File Exists
        run: |
          if [ ! -f state.txt ]; then
            echo "cbrf" > state.txt
          fi
      - name: Run App
        run: python app.py