name: Daily Very-Useful Channel

on:
  schedule:
    - cron: '5 14 * * 0' # ЦБРФ данные в 16:31 по Москве (12:31 UTC)
    - cron: '10 14 * * 0' # Мосбиржа данные в 16:35 по Москве (12:35 UTC)
  push:
    branches:
      - main

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CENNAL_ID: ${{ secrets.TELEGRAM_CENNAL_ID }}
  STATE: cbrf

jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run App CBRF
        if: github.event.schedule == '5 14 * * 0'
        run: python app.py
      - name: Run App MOEX
        if: github.event.schedule == '10 14 * * 0'
        run: python app.py