name: Daily Very-Useful Channel

on:
  schedule:
    - cron: '15 12 * * 0'  # ЦБРФ данные в 12:31 по Москве (09:31 UTC) по воскресеньям
    - cron: '20 12 * * 0'  # Мосбиржа данные в 12:35 по Москве (09:35 UTC) по воскресеньям
  push:
    branches:
      - main

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CENNAL_ID: ${{ secrets.TELEGRAM_CENNAL_ID }}

jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run App
        run: python app.py